// Table UI: seat cards, action labels, board, history, and betting controls.
// Game state and poker rules are injected; this module never mutates the game engine.
export function createTableUI({getState,$,names,pos,card,callAmt,legalActions,renderCoach,handNames,eval7}){
 function seatHTML(i){const {players,street,button,ended,handWinnerIds,board}=getState();let p=players[i],hide=i!==0&&(street!==4||p.folded);return `<div><strong>${names(i)} · ${pos(i)}${i===button?" · ●":""}</strong></div><div class="muted">$${p.stack}${p.folded?" · FOLDED":p.allin?" · ALL-IN":""}</div><div class="cards">${hide?card(null,true)+card(null,true):p.cards.map(c=>card(c)).join("")}</div><div class="actionText">${ended&&handWinnerIds.includes(i)?"WINNER"+(street===4&&board.length>=3?" · "+handNames[eval7(p.cards.concat(board))[0]]:""):p.action||""}</div><span class="chip" style="${p.streetBet?"":"visibility:hidden"}">$${p.streetBet||0} committed</span>`}
 function render(){const {players,board,street,pot,actor,paused,ended,handWinnerIds,logs,currentBet,minRaise,raiseLocked,coachVisible}=getState();
for(let i=0;i<10;i++){let el=i===0?$("hero"):$("seat"+i);el.innerHTML=seatHTML(i);el.classList.toggle("turn",!ended&&!paused&&actor===i);el.classList.toggle("folded",players[i].folded);el.classList.toggle("winner",ended&&handWinnerIds.includes(i))}$("street").textContent=["Preflop","Flop","Turn","River","Showdown"][street];$("pot").textContent="$"+pot;$("turn").textContent=ended?"Hand complete":paused?"Paused — review your decision":`${names(actor)} to act · ${pos(actor)}`;$("board").innerHTML=board.map(c=>card(c,false)).join("")+Array(5-board.length).fill('<div class="card" style="opacity:.12">?</div>').join("");$("history").innerHTML=logs.map(x=>"<div>"+x+"</div>").join("");$("history").scrollTop=$("history").scrollHeight;$("engineState").textContent=ended?"Hand finished":paused?"Waiting for Continue":("Next: "+names(actor)+" · "+pos(actor));let ht=actor===0&&!paused&&!ended;$("actions").style.display=ht?"flex":"none";let c=callAmt(0);$("checkCall").textContent=c?`Call $${c}`:"Check";$("fold").disabled=!c;$("raise").textContent=currentBet?"Raise":"Bet";$("raise").disabled=ht&&!legalActions({players,currentBet,minRaise,raiseLocked},0).raise;$("coach").classList.toggle("show",coachVisible);$("skipEnd").style.display=(!ended&&players[0].folded)?"inline-block":"none";if(players[0].cards.length)renderCoach()
 }
 return {render,seatHTML};
}
